### ISSUE TITLE
service_completed_successfully

### ISSUE THREAD

**Issue by lizzard-winner** [compose-spec/compose-spec#144]
Does the `depends_on ` condition  `service_completed_successfully ` really exist?
It doesn't seem to work for me.

```
web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: >
      sh -c "python src/manage.py collectstatic --no-input &&
             gunicorn src.core.asgi:application --reload --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      migrate:
        condition: service_completed_successfully
```

`services.web.depends_on.migrate.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
`
