### ISSUE TITLE
TOML Support for Compose Files

### ISSUE THREAD

**Issue by NickSturgeon** [compose-spec/compose-spec#152]
**What is the problem you're trying to solve**
Currently, only YAML and JSON (as a subset of YAML) are supported for writing Compose files. TOML, another popular configuration file format (`pyproject.toml`, `Cargo.toml`, ...) cannot be used.

**Describe the solution you'd like**
Allow the use of a `compose.toml` file to write Compose files. The following configurations are equivalent (taken from the Docker Compose overview):

YAML
```yaml
version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
```

TOML
```toml
version = "3.9"  # optional since v1.27.0

[services.web]
build = "."
ports = ["5000:5000"]
volumes = [".:/code", "logvolume01:/var/log"]
links = ["redis"]

[services.redis]
image = "redis"

[volumes.logvolume01]
```

**Additional context**
[More information about TOML can be found here.](https://toml.io)

Some things to consider about TOML:
- TOML doesn't allow the use of null values. In YAML, values can either be blank/null or `{}` to denote an empty key. In the comparison above, TOML's `logvolume01` is equivalent to the `{}` value in YAML. Is there anywhere where a blank value and `{}` can't be used interchangeably?
- TOML doesn't allow heterogenous arrays. It's not a huge issue but it is something to keep in mind. Consider the following YAML configuration:
```yaml
services:
  web:
    image: busybox
    ports:
      - "80-82:8080-8082"
      - 8085
      - protocol: udp
        target: 53
        published: 10053
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There is no equivalent in TOML; you would have to use the same format for specifying all port mappings.

Other projects such as Traefik allow for using either format for configuration files, which lets developers pick the best format for the situation.
