### ISSUE TITLE
Additional syntax for labels

### ISSUE THREAD

**Issue by avgas3** [compose-spec/compose-spec#166]
**What is the problem you're trying to solve**
When configuring labels in a compose file, I often have lists that look like:
```yaml
    labels:
      - traefik.http.routers.myservice.middlewares=myservice,myservice_redirect
      - traefik.http.routers.myservice.tls.certresolver=mycert
      - "traefik.http.services.myservice.loadbalancer.server.port=80"
      - traefik.http.routers.myservice.rule=Host(`myservice.mydomain.com`)
      - traefik.http.middlewares.myservice.headers.customFrameOptionsValue=ALLOW-FROM https://myservice.mydomain.com
      - traefik.http.middlewares.myservice.headers.contentSecurityPolicy=frame-ancestors 'self' mydomain.com *.mydomain.net
      - traefik.http.middlewares.myservice.headers.stsSeconds=155520011
      - traefik.http.middlewares.myservice.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.myservice.headers.stsPreload=true
      - traefik.http.middlewares.myservice_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.myservice_redirect.redirectregex.replacement=/remote.php/dav/
```
This structure is not particularly easy to read, and has a LOT of repeated text.,

**Describe the solution you'd like**
Currently, there are two working syntaxes for the labels: section of a service.

```yaml
labels:
  - traefik.enable=true
  - traefik.http.rotuers.gateway.rule=Host(`abc.mydomain.com`)
  - traefik.http.routers.gateway.tls.domains[0].main=mydomain.com
```
and 
```yaml
labels:
  - traefik.enable: "true"
  - traefik.http.rotuers.gateway.rule: Host(`abc.mydomain.com`)
  - traefik.http.routers.gateway.tls.domains[0].main: mydomain.com
```

What I think would be an excellent third option is:
```yaml
labels:
  traefik:
    enable: "true"
    http:
      routers:
        gateway:
          rule: Host(`abc.mydomain.com`)
          tls:
            domains:
              - main: example.com        

```
