### ISSUE TITLE
Allow vendor-specific extensions

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#17]
**What is the problem you're trying to solve**
Compose specification is platform-neutral, and express a generic application model. But if we don't want this to just be an academic model, but a pragmatic one people can actually use for real-world application, we need to offer a way for vendors to support custom attributes. Compose specification do allready have such a support with `x-*` extension fields on top-level elements.

**Describe the solution you'd like**
1. A generalization of the extension field support
1. Recommendation to use vendor prefixes and document known ones

Doing so one could use a compose file like this one :

```yml
service:
  backend:
    deploy:
      placement:  
        x-aws-region:   "eu-west-3"
        x-azure-region: "france-central"
```

Unrecognized `x-` attributes should be ignored, which means the same compose file can both run locally, on AWS and Azure. If this proprietary extension is widely adopted and supported by many vendors, it would make it easier to debate about inclusion in a future version of the specification.

Use of vendor prefixes also limit the risk for conflicting extensions with distinct meaning by vendors.

**Additional context**
Add any other context about the feature request here.
