### ISSUE TITLE
[Proposal] define profiles as top-level items

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#201]
**What is the problem you're trying to solve**
Compose spec introduced `profiles` as a way to make some services optional, but we still miss ability to define an "abstract" service which actual definition depends on active profile.

Typical scenario:
- on development I'd like my database to be sqlite and always start fresh new
- on CI I'd like my database to be a Mysql instance
- on Production I'd like my database to be an exiting Oracle database

I'd like I can express my `db` service to be defined by a profile.
I could use compose overrides:

compose.yaml
```yaml
services:
  foo:
    image: yolo
    depends_on:
      - db
``` 

compose-dev.yaml
```yaml
services:
  db:
    image: sqlite
``` 

but then I need to run `docker compose -f compose.yaml -f compose-dev.yaml` which is painful. I wish I could just have `dev` profile enabled (by `export COMPOSE_PROFILES=dev` set) and not have to worry about this.

If I forget to declare `compose-dev.yaml`, my compose project is invalid, missing `db` dependency.
Note that here I've declared an explicit `depends_on`, but my code might not need this dependency declared, and then `compose up` would start successfully but the app will never get a database.

**Describe the solution you'd like**

1. A way for me to declare a service as being "abstract" so that I can safely assume in my compose file this one WILL be resolved at runtime, or a nice diagnostic message will let me know something is wrong.

```yaml
services:
  foo:
    image: yolo
    require: # could be depends_on, but doesn't implies sequential start
      - db

  db: # might not be necessary as long as 'require: db' already tells us something is missing
    abstract: true
``` 

2. A simple way to define implementation for this abstract service based on active profile. As an ex-Apache Maven committer, I would suggest having top-level `profiles` for this purpose:

```yaml
services:
  foo:
    image: yolo
    require:
      - db

profiles:
  dev:
    services:
      db:
        image: sqlite
  ci:
    services:
      db:
        image: mysql
  prod:
    services:
      db:
        external: true # see https://github.com/compose-spec/compose-spec/issues/73
``` 

`compose up` could then
- know a `db` service is required, and check one is declared by some active profile
- detect two active profiles define conflicting service definitions and warn user

**Additional context**

Bonus point: 
We could (as a further discussion) introduce profiles auto-enablement based on some system observables, like OS, env var, file... (still wearing my Apache Maven user hat here :P) 

```yaml
profiles:
  foo:
    activation: 
      system: Linux
      arch: amd86
      env: FOO
      file: ~/foo
 ...
```
