### ISSUE TITLE
specify docker files inline (ie Inline dockerfile:) 

### ISSUE THREAD

**Issue by lonewarrior556** [compose-spec/compose-spec#216]
Open here as an issue from https://github.com/docker/compose/issues/8077

RIght now I have this

```
services:
  app1:
    build:
      context: ../server
      dockerfile: $PWD/a-app1.Dockerfile

  app2:
    build:
      context: ../app
      dockerfile: $PWD/b-app2.Dockerfile

  app3:
    build:
      context: ../cypress
      dockerfile: $PWD/c-app2.Dockerfile
  ```
  
  This requires me to have 3 docker files and jump around to view what's building, even though some of these are really simple. 
I would love to be able to have all the info in my `docker-compose.yml` file

```
services:
  app1:
    build:
      context: ../server
      dockerfile: |
        FROM nginx:alpine
        COPY nginx.conf /etc/nginx/nginx.conf

  app2:
    build:
      context: ../app
      dockerfile: | 
        FROM nodeJS
        COPY . .
        CMD ['npm', 'start']

  app3:
    build:
      context: ../cypress
      dockerfile: | 
        FROM cypress
        COPY . .
  ```

I don't see how it's possible to currently do this
