### ISSUE TITLE
how to mount /dev/somedrives in swarm model by compose yaml

### ISSUE THREAD

**Issue by se7enXF** [compose-spec/compose-spec#219]
**What is the problem you're trying to solve**
A clear and concise description of what the problem is.

I need to deploy a image to a PC with NPU, and want to mount a config file. To use npu, some /dev/drives must be mounted. 
So I tried below code as compose.yaml. NPU is available in container but I can not edit config file before container started.  
```yaml
# Atlas 500 Pro
version: "3.7"
services:  
  app:    
    container_name: some_name 
    image: some_image
    devices:      
        - "/dev/davinci1:/dev/davinci1"                      
        - "/dev/davinci_manager:/dev/davinci_manager"      
        - "/dev/hisi_hdc:/dev/hisi_hdc"      
        - "/dev/devmm_svm:/dev/devmm_svm"    
    volumes:      
        - "/usr/local/Ascend/driver:/usr/local/Ascend/driver"      
        - "/usr/local/dcmi:/usr/local/dcmi"      
        - "/usr/local/bin/npu-smi:/usr/local/bin/npu-smi"      
        - "/etc/hosts:/etc/hosts"      
        - "/etc/localtime:/etc/localtime"      
        - "/home/enterexitevent:/app"    
``` 
Once I found a config file can be setup in docker swarm, so I tried the upper code in swarm mode. But it seems that devices mount not work. NPU can not be read after container startup. I only found a demo for NVIDIA GPU setup in docker docs, it is not applicable for NPU. Could you please provide a demo as my expectations? In short, a config can be edited before start stack/service/container and can be read after; NPU devices can be read in container.    
Thanks!
