### ISSUE TITLE
Allow user to clarify source folder SHOULD be created if missing

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#226]
**What is the problem you're trying to solve**
Legacy [docker-compose documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3) says

> When creating bind mounts, using the long syntax requires the referenced folder to be created beforehand. Using the short syntax creates the folder on the fly if it doesn’t exist.

This is highly confusing to have such a distinction. Actually demonstrate distinct engine API used depending on adopted syntax, while the compose specification should not make such a distinction, and make it more explicit when a distinct behavior is expected.

**Describe the solution you'd like**
Introduce an explicit notation for user to ask compose implementation to create the source folder if it doesn't exists. Short syntax would imply this flag is set, while long syntax allow user to opt-in only if this is what he's expecing

```yaml
volumes:
      - type: volume
        source: mydata
        create: true  # default value when short syntax is expanded into full syntax, opt-in otherwise
        target: /data
```

**Additional context**
[Add any other context about the feature request here.](https://github.com/docker/compose/issues/9057)
