### ISSUE TITLE
Interpolation in scale value is reported as error

### ISSUE THREAD

**Issue by SoerenHenning** [compose-spec/compose-spec#227]
**What is the problem you're trying to solve**
I'm using [interpolation/expansion](https://github.com/compose-spec/compose-spec/blob/master/spec.md#interpolation) for the `scale` field as in the following example:

```yaml
version: '2.2'
services:
  example-service:
    image: busybox
    scale: ${REPLICAS:-1}
    command: ls
```

However, in VS Code the [YAML Language Support by Red Hat](https://github.com/redhat-developer/vscode-yaml) extension reports the following error:

```
Incorrect type. Expected "integer".yaml-schema: docker-compose.yml
```

**Describe the solution you'd like**
As the above snippet should be a correct Docker-Compose file (`docker-compose up` works without any issues), I expect no error to be reported.

**Additional context**
I'm not entirely sure if this is the right place to ask. If this is rather an issue with the VS Code plugin or with some other tool in the chain, please let me know.
