### ISSUE TITLE
Improve Service build section

### ISSUE THREAD

**Issue by glours** [compose-spec/compose-spec#233]
**What is the problem you're trying to solve**
A lot of issues and pull requests have been opened and asking to improve the build capabilities of the default implementation (Docker Compose).
We already have a bunch of proposals opened and pending in this specification to address some of those requests.

The objective of this issue is to aggregate the existing proposals in one place to facilitate tracking of the implementation progression.

**Describe the solution you'd like**
In the following section we'll define all the fields we want to add to the specification with links to 
- description of the property or link to the existing proposal (if exists)
- Proposal Pull Request link
- Compose-Go PR link
- Compose PR link (optional)

When working on a PR (proposal, compose-go or compose) don't forget to reference this issue

List of the property to add

- cache-to see proposal #120 
  - proposal PR #211 
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/232
- no-cache see proposal #120
  - proposal PR #232 
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/233
- platforms see proposal #120 and #197
  - proposal PR #267
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/282
- pull: `always attempt to pull a newer version of the images used during the build` boolean
  - proposal PR #232 
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/233
- secrets see proposal #81 
  - proposal PR #238 
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/236
- ssh: `SSH agent socket or keys to expose to the build, if no value provided should use the SSH_AUTH_SOCK env variable` string , see also #120 
  - proposal PR #234 
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/234
- tags: `list of the tags associated to the final build image` array, see also 
  - proposal PR #255 
  - Compose-Go PR https://github.com/compose-spec/compose-go/pull/256
- builder-options: `property to allow usage of builder specific build options, for example named context and output property of BuildX` content unspecified by the Compose specification, can be used to enable custom builder features.
  - proposal PR 
  - Compose-Go PR 

**Additional context**

Example using all this modifications
```yaml
services:
  frontend:
    image: awesome/webapp:bar     # image name to be build with a default tag name "bar"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      tags: # define tags that should be associated to the image built
        - ct-addon:foo
        - ct-addon:alp
      platforms: # define the platform targeted by the build
        - linux/amd64
        - linux/arm64
      cache-from:
        - user/app:cache
        - type=local,src=path/to/cache
      cache-to: type=local,dest=path/to/cache   # define the cache export destination
      pull: true                                # force pulling base and intermediate images use during the build
    secrets: # runtime secrets section
      - defaultsecret

  aws:
    image: ct-fake-aws:bar
    build:
      dockerfile: ./aws.Dockerfile
      ssh: default  # mount the default ssh agent
      secrets: # build secrets section
        - buildsecret
      platforms: linux/arm64
      no-cache: true                          # disabling caching for the buid process
      builder-options: # property to pass custom options to the builder
        - output: type=docker
        - no-cache-filter:
    secrets: # runtime secrets section
      - defaultsecret

secrets:
  defaultsecret:
    file: ./defaultsecret
  buildsecret:
    file: ./secret
```
