### ISSUE TITLE
Make env_file optional

### ISSUE THREAD

**Issue by ghost** [compose-spec/compose-spec#240]
**What is the problem you're trying to solve**

Because env_file is always expected to exist, when you want to run a specific usecase that doesn't use some services but requires a env_file, I need to overwrite or change the environment each time. 

It mostly happens when I run different types of CI / UnitTest.

**Describe the solution you'd like**

Allow the syntax like this.

```yaml
service:
  web:
    env_file:
      - .env
      - ?:.env.local # optional file
```

The above example is proposed by @ndeloof . Need to add parsing the elvis operator.

```yaml
env_file:
  - path: './web/.env.development.local'
    required: false  # optional file
  - path: './web/.env.local'
    required: true
```

The second example may be breaking change to existing users, but very declaritive.

**Additional context**

Relational Link

As you see below, it's been talked for so many years and gaining so many positive opinions.

- https://github.com/docker/compose/pull/3955
- https://github.com/docker/compose/issues/3560
- https://github.com/docker/compose/issues/9181

After all @deviantintegral created new issue, then @ndeloof found the issue and suggested talking in compose-specifications here. As deviantintegral looks off I created this issue.

**Comment by deviantintegral** [comment]
Thank you @ulwlu !

> The second example may be breaking change to existing users, but very declaritive.

I suppose it wouldn't be a breaking change if single values defaulted to being required? Then the default for `required:` would be `true` if unspecified.

**Comment by ulwlu** [comment]
> I suppose it wouldn't be a breaking change if single values defaulted to being required? Then the default for required: would be true if unspecified.

you are right at the point of "required", however, in second example, I added the key "path" at the same level as "required". 

If this level is a map and needs the key "path", it will still be breaking change.

```yaml
# 1
env_file:
  - ?:.env

# 2
env_file: # breaking change
  - path: .env
  - required: false # if you don't specify it will be true at default

# 3 # from my understanding, mapping below a value can't be possible.
env_file:
  - .env
  	- required: true  # if you don't specify it will be true at default
```

So, I suggest 1st example is able to avoid breaking change?

**Comment by ndeloof** [comment]
> it will still be breaking change.
There's many places we have both a "short syntax" and "long syntax",
so we could both support the existing syntax:
```yaml
env_file:
  - some.env
```
as "short notation" for extended one:
```yaml
env_file:
  - path: some.env
     required: true 
```

My proposal to introduce `?:.env` as a new notation would be more compact but might introduce some confusion.

**Comment by ulwlu** [comment]
I see, so it can be like "volume" which already existed.

```yaml
    volumes:
      - type: bind
        source: "./config"
        target: "/config"

    volumes:
      - "./config:/config"
```

It's just my opinion based on my experience, but some people might feel worried these "two ways syntax" because they sometimes behave differently. For example from above "volume" yaml, short syntax will make directory if it doesn't exist while long syntax doesn't make directory. I know this confusion should be avoided by code if specification gonna be decided so, however, I wonder if some users like me start worrying why there are two syntaxes.

It's just my aspect. I understand your worries as well.
But I think elvis operator is not so confusing to everybody, probably.

**Comment by Yogarine** [comment]
> For example from above "volume" yaml, short syntax will make directory if it doesn't exist while long syntax doesn't make directory. I know this confusion should be avoided by code if specification gonna be decided so, however, I wonder if some users like me start worrying why there are two syntaxes.

There are several other examples where the compose spec optionally allows for a more explicit syntax based on the attribute value type:
```yaml
services:
  frontend:
    image: awesome/webapp
    build: ./webapp
    depends_on:
      - db
      - redis

  backend:
    image: awesome/database
    build:
      context: backend
      dockerfile: ../backend.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
```

Now let's consider the following:

 1. Using different formats based on the attribute value type is consistent with the way several other attributes are currently implemented, and as such will cause less confusion.

 2. The `foo:bar` format is typically used when mapping `foo` to `bar`. For example:
    ```yaml
    ports:
      - "443:8043"
    volumes:
      - db-data:/etc/data
    ```
    Using this format for an arbitrary new behaviour is inconsistent and could confuse people.

 3. Switching behaviour based on the value type is cleaner and safer in terms of backwards compatibility from an architectural standpoint. Similar to how overloading a function with a different argument type is cleaner and more explicit than modifying the function to parse a string differently. There is no reason why the implementation and behaviour of existing string values should have to change.

 4. Considering the above it's also probably easier for Compose implementations to add this functionality without having to add different code paths based on parsing string contents of the `env_file` attribute.

I'd wager the second example is favourable in all ways, especially if one considers the Principle of Least Astonishment™ and wishes to prevent breakage for existing usage.

**Comment by thaJeztah** [comment]
Looking at the original use-case (running a single service from a multi-service compose file), I wonder if changes are needed at all for the syntax. Making `docker compose run` (e.g.) fail because a resource for another service isn't present feels more like bug to me.

As an example, take this compose file;

```yaml
services:
  one:
    image: nosuchimage:latest
  two:
    image: busybox
```

I'm able to `run` service `two`, even though service `one` specifies a non-existing image. Compose does not attempt to pull the image, as it doesn't need service `one`, so doesn't need its dependencies (including the image it uses);

```bash
docker compose run two
[+] Running 1/0
 ⠿ Network composeopt_default  Created                                                                                                                                                                 0.1s
/ # exit
```

However, changing the example, and adding a service `three` that uses an env-file: 

```yaml
services:
  one:
    image: nosuchimage:latest
  two:
    image: busybox
  three:
    image: nginx:alpine
    env_file: ./nosuchfile
```

Now, trying to run service `two` fails, because compose checks if the `env_file` for service `three` exists;

```bash
docker compose run two
open /Users/sebastiaan/Projects/test/composeopt/nosuchfile: no such file or directory
```

Perhaps validation of the file is a bit too eager; while it _should_ validate if the file is _well-formed_, it should not go beyond that until it's needed. For example, I _do_ expect it to fail, if I'd use a compose file like;

```yaml
services:
  one:
    image: nosuchimage:latest
    some_property_that_i_just_made_up: hello
  two:
    image: busybox
```

(which it does);

```bash
docker compose run two
services.one Additional property some_property_that_i_just_made_up is not allowed
```

I would personally consider that to be a bug; compose should not check the existence of other service's dependencies if they're not executed.


As to adding special features for this; I'm really on the fence if it's _needed_ (per the above); are there valid use-cases where you'd want a service to ignore resources that are specified, and do not exist? I.e., specify an `env_file` (and that file doesn't exist)? If the file is only required in certain environments, I think either a `touch <file>`, or better, using multiple files and having a `docker-compose-<environment>.yml` file to run for those environments would be more transparent without overly complicating the syntax.

**Comment by ulwlu** [comment]
`Making docker compose run (e.g.) fail because a resource for another service isn't present feels more like bug to me.` 

Actually I agree with this. And this happens currently. Therefore, 

`I think either a touch <file>, or better, using multiple files and having a docker-compose-<environment>.yml file`

this is a famous way to avoid the bug.

However, it's kinda troublesome because `touching file in some scripts` are messy and `making multiple yml file` leads to double maintenance. I want to use `--profile` function and combine all services inside one docker-compose, and not a few users wants same as well.

As your concern, I'm thinking it is ideal to fix a docker-compose behavior into `compose should not check the existence of other service's dependencies if they're not executed.` as you said.

**Comment by thaJeztah** [comment]
> this is a famous way to avoid the bug.

Yes, for the example given, I don't think that workaround should be needed.

For a case, where I would do `docker compose run three` (`three` being the service that defines `env_file` and the file is missing), I think that would still be the "correct" way to handle the situation; the service you're interacting with defines that it expects an `env_file`, and if that file is missing, it _should_ fail.

If you (the person maintaining the stack) knows the `env_file` is _optional_ in specific scenarios, then either `touch` the file to provide an empty one, or define a separate compose file where the dependency is defined (`docker compose -f docker-compose.yml -f docker-compose-with-envfile.yml up`)

**Comment by ulwlu** [comment]
right, I agree with that. Sorry for making it confusing, but your thought on your case is 100% same as my thought.

What the usecase I and others are saying the below.

```yml
services:
  one:
    image: nosuchimage:latest
    profile: local
  two:
    image: busybox
   profile:
     - local
     - ci
  three:
    image: nginx:alpine
    env_file: ./nosuchfile
    - ci
```

and run `docker-compose --profile local up -d` will fail becauwe three missing a file, however three doesn't belong to `profile local`.

So above example is the answer for your question `are there valid use-cases where you'd want a service to ignore resources that are specified, and do not exist?`. In this case we don't want to check the three's env_file existance.

**Comment by thaJeztah** [comment]
Yes, that seems correct (at least from my perspective). (your example would still fail due to `nosuchimage:latest` of course 😜, but I understand what you're describing 👍)

**Comment by ulwlu** [comment]
right, i fixed the example. thanks for catching.

I respect your opinion and would like to see how it goes, while I want all the comments in links in this first comment referred as well.

**Comment by deviantintegral** [comment]
> Perhaps validation of the file is a bit too eager; while it should validate if the file is well-formed, it should not go beyond that until it's needed.

This makes sense to me, and is nicely stated.

> If you (the person maintaining the stack) knows the env_file is optional in specific scenarios, then either touch the file to provide an empty one, or define a separate compose file where the dependency is defined (docker compose -f docker-compose.yml -f docker-compose-with-envfile.yml up)

Where this gets tricky is with junior developers who are learning and using Docker for the first time. In particular, they may be using IDEs like VS Code that don't provide an easy way to run compose like you mention above. And, there's typically no provision for what I'll call "pre-start" commands on the host to create the empty file.

I would suggest that most other CLI tools allow for files to optionally exist, at most producing a warning, or creating a default file in place. While I understand the idea of providing multiple compose files, we've found it takes many weeks or months for junior devs to become comfortable with it.

**Comment by joao-afs** [comment]
Is there any cons for this solution ?

```
env_file:
  - './web/.env.local' # BC since will map to "path: './web/.env.local', required: true"
  - path: './web/.env.development.local'
    required: false  # optional file
  - path: './web/.env.local'
    required: true # be explicit but not need 
```

Pros will be:
- Keeps BC, so no need for changes
- no need for scripts/touch files just because 
- fix breaking when using --profile for non related services

**Comment by Trip09** [comment]
Is there any cons for this solution ?

```
env_file:
  - './web/.env.local' # BC since will map to "path: './web/.env.local', required: true"
  - path: './web/.env.development.local'
    required: false  # optional file
  - path: './web/.env.local'
    required: true # be explicit but not need 
```

Pros will be:
- Keeps BC, so no need for changes
- no need for scripts/touch files just because 
- fix breaking when using --profile for non related services

**Comment by cphalpin** [comment]
@Trip09 I find that syntax to be the clearest and most consistent with the rest of the spec.

**Comment by bengabp** [comment]
This is my env declaration
![image](https://github.com/compose-spec/compose-spec/assets/84660669/79fbbc92-427a-4261-970d-df22cba4f714)
and i am still getting this error
![image](https://github.com/compose-spec/compose-spec/assets/84660669/bf34e4ae-3ebe-4dd3-a7db-8192f3e948da)

why is that ?

**Comment by bengabp** [comment]
> > This is my env declaration ![image](https://user-images.githubusercontent.com/84660669/277332709-79fbbc92-427a-4261-970d-df22cba4f714.png) and i am still getting this error ![image](https://user-images.githubusercontent.com/84660669/277332851-bf34e4ae-3ebe-4dd3-a7db-8192f3e948da.png)
> > 
> > why is that ?
> 
> @bengabp That syntax was just a suggestion, as far as I understand. I don't think optional env files are possible yet, in any way.

Oh 🥴

**Comment by deviantintegral** [comment]
😮 wow, it’s great to see this resolved! I’ll be looking forward to seeing this released in compose. Hope the team has a great few weeks over the holidays!

**Comment by NWarila** [comment]
Documents updated - but still a problem.

**Comment by bybatkhuu** [comment]
Is it working? Mine doesn't work...:

compose.yml:
```
  api:
    image: somerepo/somename:sometag
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
```

Output err:
```
validating /Users/someuser/workspaces/projects/test/compose.yml: services.api.env_file.0 must be a string
```


Docker version:
```
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          master
  API version:      1.44 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       54fcd40aa4de94cd75aedc5f6ebf38c6d8f92082
  Built:            Wed Nov 22 07:43:39 2023
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker compose version:
```
Docker Compose version v2.23.3-desktop.2
```
