### ISSUE TITLE
Support `services.build.pull` as `buildx bake` and `docker build --pull` does

### ISSUE THREAD

**Issue by felipecrs** [compose-spec/compose-spec#249]
**What is the problem you're trying to solve**
The base image used to build my Dockerfile is set to `latest`, which gets rebuilt every night. I need to keep my image also up to date, and the way to do that is to use `docker build --pull`, so that docker will always try to pull the base image, even if one with the same tag is already present in the local registry.

**Describe the solution you'd like**
```yaml
version: '3'
services:
  app:
    build:
      context: .
      pull: true # false by default
```

**Additional context**
This is already supported by buildx bake definition files, and is also mentioned as a caveat of docker-compose at https://docs.docker.com/engine/reference/commandline/buildx_bake/#extension-field-with-compose.

Which can, at some extent, be worked around with:

```yaml
version: '3'
services:
  app:
    build:
      context: .
      x-bake:
        pull: true
```

If you plan to use `docker buildx bake app` rather than `docker compose build app`, which is not my case.
