### ISSUE TITLE
update code-example of configs in spec.md

### ISSUE THREAD

**Issue by kodaka** [compose-spec/compose-spec#256]
**What is the problem you're trying to solve**
The Example does not show what the document want to explain for `configs` ("Short Syntax" section).

**Describe the solution you'd like**
Adding `- my_other_config` to configs of redis.
Whole example will be:

```yaml
services:
  redis:
    image: redis:latest
    configs:
      - my_config
      - my_other_config
configs:
  my_config:
    file: ./my_config.txt
  my_other_config:
    external: true
```

Updating the document to fit the example (another way to sync them) will be wrong because "Long Syntax" section already takes to explain how one config of two is granted.

**Additional context**
(nothing)
