### ISSUE TITLE
Provide service name for interpolation

### ISSUE THREAD

**Issue by ciaranmcnulty** [compose-spec/compose-spec#263]
**What is the problem you're trying to solve**

Yaml configuration can often have boilerplate, differing only by the service name. This is a small example, but in real life the repetition can be much greater:

```yaml
services:
  web:
    image: "${REGISTRY}/web:${TAG}"
    build:
      cache_from: "${REGISTRY}/web:main"
  worker:
    image: "${REGISTRY}/worker:${TAG}"
    build:
      cache_from: "${REGISTRY}/worker:main"
  [... more similar services ...]]
````

**Describe the solution you'd like**

Similar to [how the project name is exposed](https://github.com/compose-spec/compose-spec/blob/5260c1bc8ee5e93ce88412bb460924e9535d9080/spec.md#name-top-level-element), expose the service name for interpolation. 

Ideally interpolation would happen after Yaml anchors are resolved, to enable this:

```yaml
services:
  web: &template-service
    image: "${REGISTRY}/${COMPOSE_SERVICE_NAME}:${TAG}"
    build:
      cache_from: "${REGISTRY}/${COMPOSE_SERVICE_NAME}:main"
  worker: *template-service
````

**Additional context**

I made a similar request to `buildx bake`'s HCL format https://github.com/docker/buildx/issues/1156
