### ISSUE TITLE
Spec has a one-line typo in configs "short syntax" example

### ISSUE THREAD

**Issue by nopdotcom** [compose-spec/compose-spec#269]
The [short syntax example for `configs`](https://github.com/compose-spec/compose-spec/blob/a5cd401cbdca20f044d11a05707d206dbbacf22c/spec.md#short-syntax) says this:

> The following example uses the short syntax to grant the `redis` service access to the `my_config` and `my_other_config` configs.

…but it doesn’t list `my_other_config` in the actual code.

```yml
services:
  redis:
    image: redis:latest
    configs:
      - my_config
configs:
  my_config:
    file: ./my_config.txt
  my_other_config:
    external: true
```

**Describe the solution you'd like**

Add `- my_other_config` to `services.redis.configs`. 

PR incoming.
