### ISSUE TITLE
Add better support for init containers

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#291]
**What is the problem you're trying to solve**
"init containers" is a common and useful pattern to implement environment setup for a service container.
There's no such concept in the Compose model

**Describe the solution you'd like**
Actual syntax to be debated, but I assume init container basically have the same configuration as a service container, but
- implicitly inherits volumes (explicit and anonymous) from service
- inherits `deploy`

```yaml
services:
  myapp:
    image: TBD
    init:
      - image: alpine/openssl
        command: ecparam -noout -genkey -name prime256v1 -out /opt/private_key
      - image: alpine/curl
        command: -X POST http://xxx/register'
```

**Additional context**
This is a follow up for https://github.com/compose-spec/compose-spec/issues/11
