### ISSUE TITLE
inline Dockerfile

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#298]
**What is the problem you're trying to solve**
A common use-case is to customize an existing image with some minor changes. This requires a minimal Dockerfile with only a few lines. It would be nice one can declare such a Dockerfile directly inside compose.yaml, inlined

**Describe the solution you'd like**

Use yaml multiline literals with the pipe operator
We can introduce a new dedicated attrivube:
```yaml
services:
   demo:
     build:
        dockerfile-content: |
           FROM alpine
           RUN apk --no-cache add curl
```
we also can introduce a custom notation to declare inline Dockerfile
maybe we can use a custom yaml type `!inline` to mark such a block
```yaml
services:
   demo:
     build:
        dockerfile: !inline |
           FROM alpine
           RUN apk --no-cache add curl
```

**Additional context**
https://github.com/docker/compose/issues/8077

**Comment by laurazard** [comment]
This is really cool! I'd lean towards custom yaml type over adding a new attribute, but I don't have super strong feelings one way or another.

**Comment by ndeloof** [comment]
With some experiment, I noticed it's not trivial in the parser to manage proposed syntax:
```yaml
dockerfile: !inline | ... 
```
as the tag applies to the value, not the key. Would need to write:
```yaml
!inline dockerfile: | ... 
```
which sounds weird to me.

So I ended by adopting bake's `dockerfile-inline` additional key, mutually exclusive with `dockerfile`.

**Comment by thaJeztah** [comment]
I'm wondering if this will be confusing for users w.r.t. interpolating environment variables / build-args. I know there's already a lot of confusion "who's responsible" for interpolating with combinations of `env`, `env_file`, and `.env` (as well as environment variables from the current environment). Adding the Dockerfile into the compose file itself may make this even more confusing.


```yaml
services:
   demo:
     env:
       - FOO=baz       
     env_file:
       - ./a.env
     build:
        dockerfile-content: |
          # syntax=docker/dockerfile:1
          
          ARG FOO=bar
           
          FROM alpine:${FOO}
          RUN apk --no-cache add curl
          COPY <<-"eot" /app/script.sh
             echo hello ${FOO}
          eot
          RUN <<-'eot'
             echo hello ${FOO}
          eot
          RUN echo ${FOO}
        args:
          FOO: hello
          BAR: ${FOO}
```
