### ISSUE TITLE
Containers naming scheme

### ISSUE THREAD

**Issue by AhmedGrati** [compose-spec/compose-spec#301]
**What is the problem you're trying to solve**
A common use case is to allow the customization of the names of the containers. In fact, in some cases, we might have to deploy our containers, with names' prefixes/suffixes other than the default ones (the project/directory name).

**Describe the solution you'd like**
We might need to add a top-level attribute that indicates the naming scheme of our compose project. e.g:
```yaml
naming_scheme:
  prefix: no-prefix
  suffix: my-proj

services:
  foo:
    image: ubuntu
  bar:
    image: nginx
```

**Additional context**
https://github.com/docker/compose/issues/10069
