### ISSUE TITLE
Add support for configuring additional build contexts

### ISSUE THREAD

**Issue by laurazard** [compose-spec/compose-spec#306]
**What is the problem you're trying to solve**

BuildKit added the `--build-context` argument to enable users to provide additional build contexts during a build. More documentation about this can be found [here](https://docs.docker.com/engine/reference/commandline/buildx_build/#build-context).

**Describe the solution you'd like**

Being able to configure additional build contexts in a Compose file, such as:

```yaml
services:
  a:
    build:
      context: .
      build_contexts:
        - project=[a directory/image/etc.]
```

Used together with a Dockerfile such as:

```Dockerfile
# syntax=docker/dockerfile:1
FROM alpine:latest
COPY --from=project . /
```

**Additional context**
Add any other context about the feature request here.

- https://github.com/docker/compose/issues/9961 => https://github.com/microsoft/vscode-remote-release/issues/7305
