### ISSUE TITLE
Allow additional contexts to be linked to build results of other services

### ISSUE THREAD

**Issue by ciaranmcnulty** [compose-spec/compose-spec#336]
There is not currently a mechanism that allows us to explicitly use the image from one service directly in another build.

[On Slack @ndeloof pointed out this was actually possible in early docker-compose versions because images were built in explicit order so the tagged images from an 'earlier' service could be relied on]

Bake has a similar functionality ("[Linking targets](https://docs.docker.com/build/bake/build-contexts/#using-a-result-of-one-target-as-a-base-image-in-another-target)") where a special prefix can indicate an additional context refers to a build result:

```hcl
target "foo" = {}
target "bar" = {
    contexts = {
        foo-alias = "target:foo" 
    }
}
```

Compose implementations could achieve this with a similar prefix, that would allow the build result of one service to be provided as an additional context for another service.

An example of how this might be useful, consider a server-side web app: 
```yaml
services:
    app:
        build:
            [...]
```
 
 A web server might want to copy assets from that backend application:
 ```yaml
    web:
        build:
            additional_contexts:
                 base: "docker-image://nginx"
                 static-assets: "service:app"
            dockerfile_inline: >
                 FROM base
                 COPY --from=static-assets /build/static/ /var/www/html/js/
```

An accompanying service might want to add additional dependencies
```yaml
     worker:
        entrypoint: "/worker.sh"
        build:
            additional_contexts:
                 base: "service:app"
            dockerfile_inline: >
                 FROM base
                 COPY /worker/entrypoint.sh /
```

To me this syntax seems pretty clean. 

The above is possible via different combinations of build targets and YAML anchors, but I think especially in a context where some of these services might be defined across YAML files (in overrides) explicit linking makes sense.

[On Slack, @laurazard pointed out this may overlap or interact with #188] 

One implementation detail would be that if a service had no build instructions, the link would directly alias its image.
