### ISSUE TITLE
Configs inline content

### ISSUE THREAD

**Issue by bagratte** [compose-spec/compose-spec#346]
**What is the problem you're trying to solve**
Declare config content directly in compose file, inline in `configs` top-level element.

**Describe the solution you'd like**
```yaml
name: config-inline
services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /config.txt
    configs:
      - config.txt
configs:
  config.txt:
    data: |
      strawberry fields forever
```
```
$ docker compose up
[+] Running 2/2
 ✔ Network config-inline_default      Created              0.1s 
 ✔ Container config-inline-service-1  Created              0.1s 
Attaching to config-inline-service-1
config-inline-service-1  | strawberry fields forever
config-inline-service-1 exited with code 0
```
It might also be worth having base64 support.
```yaml
name: config-inline
services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /config.txt
    configs:
      - config.txt
configs:
  config.txt:
    data_base64: |
      c3RyYXdiZXJyeSBmaWVsZHMgZm9yZXZlcgo=
```
```
$ docker compose up
[+] Running 2/2
 ✔ Network config-inline_default      Created              0.1s 
 ✔ Container config-inline-service-1  Created              0.1s 
Attaching to config-inline-service-1
config-inline-service-1  | strawberry fields forever
config-inline-service-1 exited with code 0
```

**Comment by srstsavage** [comment]
File ownership/permissions probably would need to be handled as well? And it would probably make sense to either put configs in some predefined path like `/run/config/<configname>` or specify a path. But otherwise big +1.

```
name: config-inline
services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /run/config/config.txt
    configs:
      - config.txt
configs:
  config.txt:
    uid: 1000
    gid: 1050
    mode: 0400
    data: |
      strawberry fields forever
```

or

```
name: config-inline
services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /configs/config.txt
    configs:
      - config.txt:/configs/config.txt
configs:
  config.txt:
    uid: 1000
    gid: 1050
    mode: 0400
    data: |
      strawberry fields forever
```

**Comment by dmckernanacv** [comment]
I like this idea but I think the top-level block should be `files` instead of `configs` as it could technically be any file, not just for configuration.

I also think it shouldn't have it's own block within the service definition, since it's technically just a volume mount, maybe it can use standard docker volume name conventions and the compose command can check the `files` block before docker server volumes / creating a volume? 

Maybe an additional flag could specify that it's an inline file?

```
name: config-inline
services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /configs/config.txt
    volumes:
      - configfile:/configs/config.txt:inline
files:
  configfile:
    uid: 1000
    gid: 1050
    mode: 0400
    data: |
      strawberry fields forever
```

Just spitballing as I do think this feature is needed for true portability of compose files.

**Comment by ndeloof** [comment]
@srstsavage File ownership/permissions is set in service as a mount option (https://github.com/compose-spec/compose-spec/blob/master/05-services.md#long-syntax-4) ... but is actually not well supported by Docker Compose as bind mount doesn't offer such an option.

**Comment by bergkvist** [comment]
Confirmed that this is available in `Docker Compose version 2.23.1` now.

I managed to get it working like this:
```yml
version: '3.1'

services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /path/to/config.txt
    configs:
      - source: config.txt
        target: /path/to/config.txt

configs:
  config.txt:
    content: |
      strawberry fields forever
```

**Comment by Bilge** [comment]
Nice, it seems the `content` key is [completely undocumented](https://docs.docker.com/engine/swarm/configs/), and from the way it's organized, implies it only applies to Docker Swarm anyway. Moreover, it seems there is no templating support, unless you use the `golang` templating engine, which [according to the documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#configs-configuration-reference) is only supported for `docker stack`, whatever that is.

**Comment by ndeloof** [comment]
> it seems the content key is [completely undocumented](https://docs.docker.com/engine/swarm/configs/)

docker swarm does not support the compose specification and is stuck with compose file format as defined in 2020 (see https://github.com/docker/cli/issues/2527) so anything you'll read here can't be used with `docker stack`

about templating, this is a docker engine feature when swarm mode is enabled, so doesn't apply to docker compose (which run client side)

**Comment by polarathene** [comment]
> Nice, it seems the `content` key is [completely undocumented](https://docs.docker.com/engine/swarm/configs/), and from the way it's organized, implies it only applies to Docker Swarm anyway.

Documentation for this feature is covered here: https://docs.docker.com/compose/compose-file/08-configs/#example-2

![image](https://github.com/compose-spec/compose-spec/assets/5098581/2b8807a8-8eeb-4d15-9e20-295e393786da)

![image](https://github.com/compose-spec/compose-spec/assets/5098581/fa76d8b9-499c-44ec-9806-788876f1ac86)

---

What is not documented is that [it requires v2.23.1 of Docker Compose](https://github.com/compose-spec/compose-spec/pull/429#issuecomment-1828925468) from mid November, nor is the feature itself announced in the release notes of Docker Compose.

If you rely on Docker Desktop there is no release yet that includes that ([presently v2.23.0](https://docs.docker.com/desktop/release-notes/#4250)). Not quite sure how a feature is part of a patch version, but it is 😅 

---

PR for docs raised: https://github.com/compose-spec/compose-spec/pull/446

**Comment by andoks** [comment]
When I run docker compose v2.23.3 (with docker client/server version 24.0.5), the configs that are specified as content and environment ends up in `/run/secrets/` instead of in `/` - should I report this as bugs?

command
```
export ENV_VARIABLE="some content in variable"; docker-compose run test
```

docker-compose.yml
```yml
version: "3.6"

services:
  test:
    image: "bash:latest"
    command: "bash -c 'whoami; ls -la /; cat /environment.txt; cat /content.txt; cat file.txt; cat /.dockerenv; find / -name content.txt;'"
    configs:
      - environment.txt
      - content.txt
      - file.txt

configs:
  environment.txt:
    environment: "ENV_VARIABLE"
  content.txt:
    content: "content inline"
  file.txt:
    file: "file.txt"
```

file.txt
```
some file
```


<details>
<summary>docker version</summary> 

```
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.3
 Git commit:        24.0.5-0ubuntu1~22.04.1
 Built:             Mon Aug 21 19:50:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       24.0.5-0ubuntu1~22.04.1
  Built:            Mon Aug 21 19:50:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~22.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

</details>

**Comment by ndeloof** [comment]
@andoks that's a regression, I'll fix this ASAP
in the meantime, you can define config references in your services to use an explicit target path

**Comment by bagratte** [comment]
@ndeloof Thank you for implementing this.
What's the reasoning behind naming the key `content`. Honestly, `data` seemed more professional to me. Apart from that subjective view, Kubernetes ConfigMaps and Secrets use `data`. Is it too late to change this? Also, why did base64 support not end up in this implementation?

**Comment by andoks** [comment]
@ndeloof I get the error 'configs.environment.txt Additional property environment is not allowed' when trying to use the configs from environment feature with compose version v2.17.0 BTW. Maybe it too should be documented when was introduced to docker compose?

**Comment by andoks** [comment]
> @andoks that's a regression, a fix has been proposed: [docker/compose#11232](https://github.com/docker/compose/pull/11232) in the meantime, you can define config references in your services to use an explicit target path

What do you mean by "config references"? AFAICS there is no way to override the path of the configs in anyway (https://github.com/compose-spec/compose-go/blob/402d2a34c2f0914cb7bb81a7829624f28b797dda/types/types.go#L688C6-L688C22)

**Comment by bagratte** [comment]
Binary data is the use case for base64. That is also why `data` and `data_base64` look prettier rather than `content` and, eventually, `content_base64`.

**Comment by ndeloof** [comment]
Binary data are obviously created/managed by another tool, and as such would better be stored inside a dedicated file (as already supported). Assuming we decide to add support for base64-encoded content, this might not require a new attribute, just an alternate syntax
```yaml
configs:
  foo:
    content:
      encoding: base64
      value: ...
```

**Comment by bagratte** [comment]
That's fine. `content` or `data` is not a big deal as long as the functionality is there. So thanks again for all your work, @ndeloof 

Mimicking Kubernetes was never my intention. This issue was born from a genuine need in a purely local compose project. Still, consistency across somewhat similar products helps. I think it would help if you communicated your thought process before implementing this. That's all the little OCD's we all programmers have.

Thanks again for everything you do for this project. Secrets inline content is next :)

**Comment by andoks** [comment]
> Binary data are obviously created/managed by another tool, and as such would better be stored inside a dedicated file (as already supported). Assuming we decide to add support for base64-encoded content, this might not require a new attribute, just an alternate syntax
> 
> ```yaml
> configs:
>   foo:
>     content:
>       encoding: base64
>       value: ...
> ```

Or maybe even having encoding as a top-level field to support alternative encodings in the other formats too maybe.

```yaml
configs:
  foo-content:
    encoding: "base64"
    content: "..."
  foo-file:
    encoding: "base64"
    file: "path-to-base64-encoded-file"
  foo-env:
    encoding: "base64"
    environment: "VARIABLE_WITH_BASE64_ENCODED_CONTENT"
```

**Comment by Bilge** [comment]
This feature just landed in Docker Desktop for Windows but I absolutely cannot get variable substitutions to work. It's obviously making an attempt, because I get an error about the variable not being set (although it is, but in the service config, not the calling context), and that it will thus default to a blank string; yet it does not, it just gets dumped into the file verbatim, neither substituted with the service value nor a blank string.

**Comment by ndeloof** [comment]
@Bilge `environment` variables set in service context are only used to set _container_'s environment, they have no impact on variable interpolation while parsing compose.yaml file:
```
$ cat compose.yaml 
services:
  test:
    image: alpine
    configs:
      - test
    command: cat /test

configs:
  test:
    content: |
      hello ${WORLD}

$ docker compose run test
WARN[0000] The "WORLD" variable is not set. Defaulting to a blank string. 
hello 

$ WORLD=Bilge docker compose run test
hello Bilge
```

**Comment by Bilge** [comment]
I was starting to figure that out, but it is regrettable it works that way. I was seeing the same, except my output was `hello ${WORLD}`, despite the warning suggesting it would be replaced with the blank string (on Docker Desktop Win 4.26.0 with Docker Compose version v2.23.3).

Aside, it was very nice of you to dedicate your example to me ❤️

**Comment by polarathene** [comment]
On that topic of the [interpolation feature](https://docs.docker.com/compose/compose-file/12-interpolation/), as shown in the example in https://github.com/compose-spec/compose-spec/pull/446 where the inline content is unintentionally interpreted, would it be worth opening a feature request for a complimentary option to opt-out of interpolation on the content, or is that something that must be applied to the YAML document as a whole?

Minor benefit of not having to escape a `$` with `$$`, so not too important (_especially when the docs with that advice is organized a little better_).

**Comment by ndeloof** [comment]
One reason we introduced `content` is to enable variable interpolation. If you want to preserve a config from interpolation, and/or have issues with `$` character used in your config, better just move it to a dedicated file.

**Comment by Paxa** [comment]
It was introduced here https://github.com/docker/compose/pull/10343 and works like this:

```yaml
  service_name:
    build:
      context: .
      dockerfile_inline: |
          FROM ruby:3-alpine
          WORKDIR /app
          ...
```

**Comment by Nthalk** [comment]
Being defined, and being supported is different. Latest `docker compose` works with it, but not `docker swarm` / `docker stack`.

Given this simple config:

```YAML
services:
  test:
    image: debian:bookworm-slim
    command: | 
      bash -c "
      cat ./test-config
      "
    configs:
      - target: ./test-config
        source: test-config
configs:
  test-config:
    content: |
      this is a test!
```

Works with an updated docker compose:
```BASH
➤ docker compose up
Attaching to test-1
test-1  | this is a test!
test-1 exited with code 0

```

Doesn't work with docker swarm / stack:
```BASH
➤ docker stack deploy --compose-file docker-compose.yaml test
configs.test-config Additional property content is not allowed
```

Given the latest version I could find
```BASH
➤ docker info
Client:
 Version:    27.2.1-rd
 Context:    desktop
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.6.0
    Path:     /Users/nthalk/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.25.0-desktop.1
    Path:     /Users/nthalk/.docker/cli-plugins/docker-buildx
  cloud: Docker Cloud (Docker Inc.)
    Version:  v0.4.2
    Path:     /Users/nthalk/.docker/cli-plugins/docker-cloud
  compose: Docker Compose (Docker Inc.)
    Version:  v2.38.1-desktop.1
    Path:     /Users/nthalk/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.41
    Path:     /Users/nthalk/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.1.11
    Path:     /Users/nthalk/.docker/cli-plugins/docker-desktop
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.29
    Path:     /Users/nthalk/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/nthalk/.docker/cli-plugins/docker-init
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.9.3
    Path:     /Users/nthalk/.docker/cli-plugins/docker-mcp
  model: Docker Model Runner (EXPERIMENTAL) (Docker Inc.)
    Version:  v0.1.32
    Path:     /Users/nthalk/.docker/cli-plugins/docker-model
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nthalk/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.18.1
    Path:     /Users/nthalk/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/nthalk/.docker/cli-plugins/docker-dev" is not valid: failed to fetch metadata: fork/exec /Users/nthalk/.docker/cli-plugins/docker-dev: no such file or directory
WARNING: Plugin "/Users/nthalk/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/nthalk/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 28.3.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: active
  NodeID: qm6anuau6h4o08jzxjfrtd8mm
  Is Manager: true
  ClusterID: t5p24bf4x1w7lhnv77bponyys
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.76
  Manager Addresses:
   192.168.1.76:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-63-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 125.7GiB
 Name: desktop
 ID: 8ee0ddfa-dc6d-4d98-8374-f02538fc8ee1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

```
