### ISSUE TITLE
Service volumes incorrect information?

### ISSUE THREAD

**Issue by bagratte** [compose-spec/compose-spec#347]
Consider https://github.com/compose-spec/compose-spec/blob/853d1a9b2301c20b76b867a22b4ef0faef79362e/05-services.md?plain=1#L1609-L1613
Consider also the following perfectly valid compose file:
```yaml
services:
  service1:
    image: ubuntu
    command: ls /tmp/service1
    volumes:
      - /tmp:/tmp/service1
  service2:
    image: ubuntu
    command: ls /tmp/service2
    volumes:
      - /tmp:/tmp/service2
```
Does this compose file not contradict what is stated in Compose Specification? The mounts are the same host path and they are used in multiple services.

**Comment by laurazard** [comment]
There's no contradiction here – I assume what's throwing you off is the part of the spec you quoted which states
```[...]only used by a single service[...]```.

The following Compose file:
```yaml
service1:
    volumes:
        - /tmp:/tmp/service2
[...]
service2:
    volumes:
        - /tmp:/tmp/service2
```
defines two individual mounts, one for each service, that happen to refer to the same host path. These mounts are TWO separate, unique mounts – and as such not being used in multiple services.

What the part of the Spec you quoted is trying to convey here is that, if you want to use a volume mount/other type of mount, in two separate service definitions, you must declare the (for example, named volume) outside of the service definition, and then simply refer to it, otherwise when you declare it inside the service definition what you're doing is creating two separate mounts, that happen to be for the same path.

Feel free to open a PR to make that wording clearer!

**Comment by bagratte** [comment]
I'm still confused. Could you please give an example of  the same mount in two separate service definitions with a volume declaration outside of the services?

**Comment by laurazard** [comment]
> I'm still confused. Could you please give an example of the same mount in two separate service definitions with a volume declaration outside of the services?

Sure:
```yaml
services:
  backend:
    image: awesome/database
    volumes:
      - db-data:/etc/data

  backup:
    image: backup-service
    volumes:
      - db-data:/var/lib/backup/data

volumes:
  db-data:
```
(I copied this from https://github.com/compose-spec/compose-spec/blob/853d1a9b2301c20b76b867a22b4ef0faef79362e/07-volumes.md#volumes-top-level-element)

---------------

I think you might need some context:

The top-level `volumes` key (as described [here](https://github.com/compose-spec/compose-spec/blob/853d1a9b2301c20b76b867a22b4ef0faef79362e/07-volumes.md#volumes-top-level-element) is meant for defining named volumes:
```
Volumes are persistent data stores implemented by the platform. The Compose specification offers a neutral abstraction for services to mount volumes, and configuration parameters to allocate them on infrastructure.

The volumes section allows the configuration of named volumes that can be reused across multiple services. Here's an example of a two-service setup where a database's data directory is shared with another service as a volume named db-data so that it can be periodically backed up:
```

The service-level `volumes` key allows you to use mount one of the volumes defined in the top-level volumes key into a service container (such as in the example I provided above) **but it also** allows you to define a simple bind mount from the host into the container such as your example:

```yaml
services:
  service1:
    volumes:
      - /tmp:/tmp/service1
```

-------------------

That said, what the Specification is saying here:
```
 If the mount is a host path and only used by a single service, it MAY be declared as part of the service 
 definition instead of the top-level `volumes` key. 
```

Is that if your mount is a host path (not a named volume) and you don't need to share it with other services, you can declare it directly in the service definition.
