### ISSUE TITLE
Suggest adding the description of domainname of compose

### ISSUE THREAD

**Issue by wushu037** [compose-spec/compose-spec#358]
File: [05-services.md](https://docs.docker.com/compose/compose-file/05-services/)

I tried to configure the domainname directly, for example
```yml
services:
  centos1:
    image: centos:7
    domainname: "a.b.com"
    command: "ping localhost" # keep container running
  centos2:
    image: centos:7
    command: "ping localhost"
```

but can't execute `ping a.b.com` successfully on centos2

I'm not alone in having this problem, is the documentation missing the necessary description?
