### ISSUE TITLE
include statement does not work a the top-level. 

### ISSUE THREAD

**Issue by nelson-lark** [compose-spec/compose-spec#398]
File: [14-include.md](https://docs.docker.com/compose/compose-file/14-include/)

I can not write a docker compose file that looks like this, as implied by the article:
```
version: '3.9'

include:
  - path: my-service/my-service.yaml
    project_directory: .
```

I'm not really sure under what conditions the include statement does work, but definitely not at the top level of a docker-compose project.
