### ISSUE TITLE
Intended behaviour is unclear when merging compose files which also extend others

### ISSUE THREAD

**Issue by cphalpin** [compose-spec/compose-spec#415]
**What is the problem you're trying to solve**
I've opened an issue (github.com/docker/compose/issues/10946) in the docker/compose repo for behaviour I consider a bug but have been told it's expected.

I have a main compose file which defines a service "app" with a build context. A second compose file extends "app" from the "app-base" service in a third compose file. In the third file "app-base" has a build section defining some build args but no context. When this is all merged I expected the build context to still be the value from the main compose file since it was not explicitly set in the "app-base" service.

**Describe the solution you'd like**
Clarify what the expected behaviour is and update the docs accordingly.

**Comment by cphalpin** [comment]
`compose/main.yml`:

```yaml
services:
  app:
    build:
      context: ..
```

`compose/dev.yml`:

```yaml
services:
  app:
    extends:
      file: abstract/dev.yml
      service: app-base
```

`compose/abstract/dev.yml`:

```yaml
services:
  app-base:
    build:
      args:
        var: val
```

When running `docker compose -f compose/main.yml -f compose/dev.yml config` I expect the build context path of the `app` service to be the parent directory of `compose` but have been told that it should be `compose/abstract`
