### ISSUE TITLE
Optional include files

### ISSUE THREAD

**Issue by kaznovac** [compose-spec/compose-spec#424]
**What is the problem you're trying to solve**
I'd like to have optional include files to enable optional services override (e.g. developer specific configuration that should not be committed)

**Describe the solution you'd like**
```yaml
include:
  - ../commons/compose.yaml
  - path: ../commons/compose-long.yaml
    project_directory: ..
    env_file: ../another/.env
  - ../another_domain/compose.yaml
  - path: ./docker-compose.local.yaml
    required: false # <-- propose to implement this --

services:
  webapp:
    # ...
```

**Additional context**
Similar solution to #240

But I'm not for the short optional syntax - as it hinders readability
