### ISSUE TITLE
Include files marked as `Invalid type. Expected "include"`

### ISSUE THREAD

**Issue by BenjaminNolan** [compose-spec/compose-spec#462]
**What is the problem you're trying to solve**
I have a `compose.yml` file which includes other `./path/to/compose.yml` files relative to itself. These includes work correctly with `docker compose`, however they are flagged with the error `Invalid type. Expected "include"` by `yaml-schema` using the `compose-spec.json` file located within this repo's main branch as accessed via https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json.

**Describe the solution you'd like**
`compose-spec.json` needs to be updated to specify the correct format for `include:`.

**Additional context**
example `compose.yml`:

```yaml
version: "3"

include:
  - "./docker/pgadmin/compose.yml"
  - "./docker/portainer/compose.yml"
  - "./docker/postgres/compose.yml"
  - "./docker/zipkin/compose.yml"

services:
  backend:
    container_name: backend
    image: ghcr.io/path/to/backend:latest
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
```

![image](https://github.com/compose-spec/compose-spec/assets/642271/011c29e2-3311-4926-a0e4-7c199fb941a9)

![image](https://github.com/compose-spec/compose-spec/assets/642271/bf779af9-9145-47ea-baf7-9dbe2d81a766)
