### ISSUE TITLE
Custom shared volume path with project_name

### ISSUE THREAD

**Issue by hurvajs77** [compose-spec/compose-spec#492]
I tryied use shared volume path for better manipulation with data (primarily for databases). But it seems doesn't work. It work only for volumes without target path definition.

I've this one:
```yaml
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/hurvajs/Sites/__data__ # <-- I wanna stored all DB, settings etc. on custom path, but separated by project name
      o: bind
```

Is possible?

Thanks for advice :-)
