### ISSUE TITLE
Using <service>.develop.watch without a <service>.build section does not initialise watches

### ISSUE THREAD

**Issue by sdolemelipone** [compose-spec/compose-spec#505]
**What is the problem you're trying to solve**

If a watch is defined for a service with action `sync` or `sync+restart`, but the service does not have a `build` section, the watch is ignored/not initialised.
E.g. running `docker compose up --watch` with the below configuration does not cause a watch to be set up. 
```yaml
my-service:
  image: myimage
  develop:
    watch:
      - path: ./app
        action: sync+restart
        target: /home/web/app  
```
If a `build` section is defined for the service, then the watch is initialised correctly:
```yaml
my-service:
  image: myimage
  build: app
  develop:
    watch:
      - path: ./app
        action: sync+restart
        target: /home/web/app  
```

**Describe the solution you'd like**

_Either_:
- update of the documentation to reflect this

_or ideally_:
- allow `sync` and `sync+restart` to run without a `build` section being defined.

**Additional context**

I expect there are many use cases where a watch would be required without a build step. One such example is a main service with a complicated build step, then a number of secondary services which use the same image (but do not re-define the build steps from the main service).

Thanks.
