### ISSUE TITLE
Introduce solution to missing YAML functionality for sequence extensions

### ISSUE THREAD

**Issue by andrewvaughan** [compose-spec/compose-spec#512]
**What is the problem you're trying to solve**
With more and more services configuring through Docker labels (e.g., https://github.com/traefik/traefik) the copy/paste needed to make Compose files gets quickly out of hand.

As mentioned in the Compose spec (https://github.com/compose-spec/compose-spec/blob/master/10-fragments.md?plain=1#L83), and specifically discussed in https://github.com/yaml/yaml/issues/35, this is a shortcoming that there have started to be anti-patterns showing in the community to work around.

It would be helpful if Docker could introduce functionality that could reduce copy/pasting of sequences, given the growing use-case for them.

I realize it's not ideal to have to make up for the shortcomings of the chosen markup language, but this is actually the recommendation from the YAML spec maintainers mentioned in the ticket above - in that each processor should determine a way to compute this on their own.

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.

**Additional context**
An optimal way to solve this would be with YAML templates - not regressing to the "Extensions" from v2. For example, this:

```yaml
services:

  my-first-traefik-service:
    # ...

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"

      - "traefik.http.services.app1.loadbalancer.server.port=9000"

      - "traefik.http.routers.app1.rule=Host(`my.first.app.fqdn.example.com`)"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=lets-encrypt"

      - "traefik.http.routers.app1-http.entrypoints=web"
      - "traefik.http.routers.app1-http.rule=Host(`my.first.app.fqdn.example.com`)"
      - "traefik.http.routers.app1-http.middlewares=redirect-to-https@file"

  my-second-traefik-service:
    # ...

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"

      - "traefik.http.services.app2.loadbalancer.server.port=8080"

      - "traefik.http.routers.app2.rule=Host(`my.second.app.fqdn.example.com`)"
      - "traefik.http.routers.app2.entrypoints=websecure"
      - "traefik.http.routers.app2.tls.certresolver=lets-encrypt"

      - "traefik.http.routers.app2-http.entrypoints=web"
      - "traefik.http.routers.app2-http.rule=Host(`my.second.app.fqdn.example.com`)"
      - "traefik.http.routers.app2-http.middlewares=redirect-to-https@file"
```

At minimum, you can see the repitition in the labels that can be reduced if sequences had a solution, but with a more comprehensive templating solution, you could seriously improve this for users:

```yaml
services:

  my-first-traefik-service:
    # ...

      labels:
        from_template:
          id: traefik-app-labels
          variables:
            APP_NAME: app1
            CONTAINER_PORT: 9000
            FQDN: my.first.app.fqdn.example.com
          extend:
            - "foo=bar"

  my-second-traefik-service:
    # ...

    labels:
      from_template:
        id: traefik-app-labels
          variables:
            APP_NAME: app2
            CONTAINER_PORT: 8080
            FQDN: my.second.app.fqdn.example.com
          extend:
            - "biz=bang"

templates:
  traefik-app-labels:
    - "traefik.enable=true"
    - "traefik.docker.network=reverse-proxy"

    - "traefik.http.services.{APP_NAME}.loadbalancer.server.port={CONTAINER_PORT}"
 
    - "traefik.http.routers.{APP_NAME}.rule=Host(`{FQDN}`)"
    - "traefik.http.routers.{APP_NAME}.entrypoints=websecure"
    - "traefik.http.routers.{APP_NAME}.tls.certresolver=lets-encrypt"

    - "traefik.http.routers.{APP_NAME}-http.entrypoints=web"
    - "traefik.http.routers.{APP_NAME}-http.rule=Host(`{FQDN}`)"
    - "traefik.http.routers.{APP_NAME}-http.middlewares=redirect-to-https@file"
```

By offering template capability, this significantly increases the flexibility of the file beyond what even YAML anchors are capable of. The YAML community has outright said that introducing anchors was a mistake, and that programatic controls should be entirely within the design of the processing application (i.e., Docker Compose), so no further development should ever be expected from the YAML spec.

I don't have the exact knowledge of what patterns might be doable, but my hope is this offers a launching off point. Thanks for considering!
