### ISSUE TITLE
Absolute target path breaks build secrets

### ISSUE THREAD

**Issue by craigds** [compose-spec/compose-spec#537]
**What is the problem you're trying to solve**

Specifying an absolute path for a secret's `target` in `services.{service}.build.secrets` will cause the secret to be silently ignored, and the build may fail.

A workaround is to not define a `target` path in the compose file at all - dockerfiles can specify an absolute path in their RUN instructions.

**Describe the solution you'd like**

Either of:

1. make absolute paths work (not sure why they don't)
2. update the docs to be 100% clear that build secrets can't support absolute target paths (note: runtime secrets _do_ support absolute target paths)
3. remove the `target` property altogether for build secrets (it's probably redundant since Dockerfile can specify a target path)

**Additional context**

```
---
secrets:
  mysecret:
    environment: "MYSECRET"

services:
  myservice:
    build:
      context: .
      secrets:
        - source: mysecret
          target: /root/mysecret
```

```
$ MYSECRET=abc docker compose build --no-cache myservice
#0 building with "orbstack" instance using docker driver

#1 [myservice internal] load build definition from Dockerfile
#1 transferring dockerfile: 185B done
#1 DONE 0.0s

#2 [myservice internal] load metadata for docker.io/library/alpine:latest
#2 DONE 0.7s

#3 [myservice internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [myservice stage-0 1/2] FROM docker.io/library/alpine:latest@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
#4 CACHED

#5 [myservice stage-0 2/2] RUN --mount=type=secret,id=mysecret,required=true,target=/root/mysecret     cat /root/mysecret
#5 ERROR: secret mysecret: not found
------
 > [myservice stage-0 2/2] RUN --mount=type=secret,id=mysecret,required=true,target=/root/mysecret     cat /root/mysecret:
------
failed to solve: secret mysecret: not found
```

**Comment by ndeloof** [comment]
`target` for a build.secret is not the mount path to be used during the build, which is set in the Dockerfile as a `--mount` parameter, but the ID used in this same Dockerfile.

In your example, Dockerfile could use `RUN --mount=type=secret,id=apikey,required=true,target=/root/apikey` and you would declare compose.yaml as:
```yaml
secrets:
  mysecret:
    environment: "MYSECRET"

services:
  myservice:
    build:
      context: .
      secrets:
        - source: mysecret
          target: apikey
```
