### ISSUE TITLE
Proposal: Introduce named mappings for pre-defined variables

### ISSUE THREAD

**Issue by Vigilans** [compose-spec/compose-spec#553]
# Overview

A new syntax `${name[key]}` is introduced to interpolation, to allow for compose to expose its internal information to configuration files, as what https://github.com/compose-spec/compose-spec/issues/248 describes.

For example:
* `${project[working-dir]}`: The project's directory
* `${compose[config-dir]}`: The directory where the compose file using this variable is located
* `${compose[replica-index]}`: The container/resource's index number of current replicated service/resource
* `${image[user]}`: The user specified in the image of current service's current container
* `${labels[label.name]}`: The value of the label `label.name` in the specifying container/resource
* `${container[env][VAR_NAME]}`: The value of the env var `VAR_NAME` in the specified container
* `${secrets[secret-key-or-name]}`: The content of the specified secret `secret-key-or-name`
* `${containers[container-name][image]}`: The image of the specified container `container-name`
* `${services[service-name][containers][0][env][VAR_NAME]}`: The value of the env var `VAR_NAME` in the first container of the specified service `service-name`

# Tracking Pull Requests

This proposal's implementation is split into multiple pull requests in sequence:

* [Vigilans/compose-go#1](https://github.com/Vigilans/compose-go/pull/1): Introduce named mappings to template substitution
* [Vigilans/compose-go#2](https://github.com/Vigilans/compose-go/pull/2): Introduce named mappings to interpolation
* [Vigilans/compose-go#3](https://github.com/Vigilans/compose-go/pull/3): Introduce named mappings to model loading, with properly implemented interpolate after merge
* (WIP, needs discussion with developers for data layout): Support replicated service/resource in named mappings.

Each pull request focus on a specific module in `compose-go`, along with that:
1. Keeps compatible with existing codebase. No change to public API, and named mappings are opt-in only if specified by downstream caller.
2. Heavily tested. Around 67% of the changed lines are written for tests.
3. Each commit in the PR is carefully rebased and organized for better review experience. Therefore please review each PR **_commit by commit_**.

# Related Issues

* https://github.com/compose-spec/compose-spec/issues/248
* https://github.com/compose-spec/compose-go/issues/335
* https://github.com/docker/compose/issues/3874
* https://github.com/docker/compose/issues/9026
* https://github.com/docker/compose/issues/3722

**Comment by Vigilans** [comment]
# Currently supported varibles (Global/Common information)

## Project

### `${project[name]}`

Name of the project.

### `${project[working-dir]}`

The project's directory.

## Compose

### `${compose[version]}`

The version of docker compose.

### `${compose[root-dir]}`

The directory where docker compose is calling. Will never change whatever current compose file's context is.

### `${compose[config-dir]}`

The directory where the compose file using this variable is located.

Solves issues:
* https://github.com/compose-spec/compose-go/issues/335

### `${compose[working-dir]}`

Exactly behaves the same as `.` in compose file's pathes.

### `${compose[replica-index]}`

The container/resource's index number of current replicated service/resource, starting at 0.

Solves issues:
* https://github.com/docker/compose/issues/9026
* https://github.com/docker/compose/issues/3722

### `${compose[replica-index-1]}`

Works the same as `${compose[replica-index]}`, but starting at 1.

## Labels

### `${labels[label.name]}`

The value of the label `label.name` in the specifying container/resource. Shortcut for things like `${container[labels][label.name]}`.

**Comment by Vigilans** [comment]
# Currently supported varibles (Service/Resource scope information)

## Service

### `${service[name]}`

The name of the service.

### `${service[scale]}`

The number of replicas of the service.

### `${service[containers][...][...]}`

Referencing containers of the service, can be used like `${service[containers][0][name]}`.

## Container

### `${container[name]}`

The name of the container.

### `${container[image]}`

The image name of the container.

### `${container[user]}`

The user of the container. Default to `${image[user]}` if not specified in compose config.

### `${container[working-dir]}`

The working directory of the container. Default to `${image[working-dir]}` if not specified in compose config.

### `${container[env][VAR_NAME]}`

The value of the env var `VAR_NAME` in the specified container. Default to `${image[env][VAR_NAME]}` if not specified in compose config.

### `${container[labels][label.name]}`

The value of the label `label.name` in the specifying container. Default to `${image[labels][label.name]}` if not specified in compose config.

## Image

### `${image[name]}`

The name of the image.

### `${image[user]}`

The user specified in the image.

### `${image[working-dir]}`

The working directory specified in the image.

### `${image[env][VAR_NAME]}`

The value of the env var `VAR_NAME` in the specified image.

### `${image[labels][label.name]}`

The value of the label `label.name` in the specifying image.

## Network

### `${network[name]}`

The name of the network.

### `${network[external]}`

Whether the network is external. Returns `true` or `false`.

### `${network[driver]}`

The driver of the network.

### `${network[labels][label.name]}`

The value of the label `label.name` in the specifying network.

## Volume

### `${volume[name]}`

The name of the volume.

### `${volume[external]}`

Whether the volume is external. Returns `true` or `false`.

### `${volume[driver]}`

The driver of the volume.

### `${volume[labels][label.name]}`

The value of the label `label.name` in the specifying volume.

## Config

### `${config[name]}`

The name of the config.

### `${config[external]}`

Whether the config is external. Returns `true` or `false`.

### `${config[file]}`

The referencing file path of the config.

### `${config[environment]}`

The referencing environment variable of the config.

### `${config[content]}`

The literal content of the config.

### `${config[data]}`

The content of the config by resolving file/environment/content.

### `${config[labels][label.name]}`

The value of the label `label.name` in the specifying config.

## Secret

### `${secret[name]}`

The name of the secret.

### `${secret[external]}`

Whether the secret is external. Returns `true` or `false`.

### `${secret[file]}`

The referencing file path of the secret.

### `${secret[environment]}`

The referencing environment variable of the secret.

### `${secret[data]}`

The content of the secret by resolving file/environment.

### `${secret[labels][label.name]}`

The value of the label `label.name` in the specifying secret.

**Comment by Vigilans** [comment]
# Currently supported varibles (Cross-scope referencing)

## Services

### `${services[service-name][...]}`

Referencing another service, can be used like `${services[service-name][containers][0][name]}`.

## Containers

### `${containers[container-name][...]}`

Referencing another container, can be used like `${containers[container-name][env][VAR_NAME]}`.

## Networks

### `${networks[network-name][...]}`

Referencing another network, can be used like `${networks[network-name][driver]}`.

## Volumes

### `${volumes[volume-name][...]}`

Referencing another volume, can be used like `${volumes[volume-name][driver]}`.

## Configs

### `${configs[config-name][...]}`

Referencing another config, can be used like `${configs[config-name][data]}`, abbreviated as `${configs[config-name]}` for easy of use.

## Secrets

### `${secrets[secret-name][...]}`

Referencing another secret, can be used like `${secrets[secret-name][data]}`, abbreviated as `${secrets[secret-name]}` for easy of use.

**Comment by Vigilans** [comment]
## What potential can this feature unlock?

### `extends` snippet can have placeholder template that varies between services/included projects

E.g. by using `include`, each included config has different project name, and we can have a common snippet with some fields interpolated based on the project that includes it:
```yaml
services:
  common:
    profiles:
      - ${labels[nas.profile]}
    container_name: nas.${service[name]}
    network_mode: service:${project[name]}-ingress
    restart: unless-stopped
    logging:
      driver: local
    tmpfs:
      - "/tmp:exec,mode=0777"
      - "/run:exec,mode=0777"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      nas.profile: ${project[name]}
```

### Replicated containers in a service can have diverse fields (e.g. name, volumes) 

By using `${container[replica-index]}`, a service field can have it interpolated to different values for each container. E.g.
```yaml
services:
  service:
    scale: 3
    container_name: nas.${service[name]}-${container[replica-index]}
    volumes:
      - volume-${container[replica-index]}

volumes:
  volume:
    name: volume-${volume[replica-index]}
    scale: ${services[service][scale]} # This field is not available yet, but is proposed in this proposal
```

### Fields like environment variable can have its content derived from config/secret

We have config/secret from environment variable, but not the other way around. Deriving environment variable from secret can be very helpful when an application's image accepts `VAR` environment but does not support `VAR_FILE` format. E.g.
```yaml
  pgweb:
    image: sosedoff/pgweb:latest
    extends:
      file: ${compose[root-dir]}/base/compose.common.yml
      service: common
    entrypoint: /usr/bin/pgweb
    command:
      - --bind=0.0.0.0
      - --listen=5433
      - --host=127.0.0.1
      - --port=5432
      - --user=${secrets[postgres_username]}
      - --passfile=/run/secrets/postgres_password
      - --db=${secrets[postgres_username]}
    environment:
      PGWEB_AUTH_USER: ${secrets[admin_username]}
      PGWEB_AUTH_PASS: ${secrets[admin_password]}
    labels:
      - nas.caddy.${project[name]}=https://postgres.${project[name]}.nas.mydomain
      - nas.caddy.${project[name]}.import=auth
      - nas.caddy.${project[name]}.reverse_proxy=127.0.0.1:5433
    depends_on:
      - ${project[name]}-postgres
    secrets:
      - postgres_username
      - postgres_password
```

**Comment by ndeloof** [comment]
Interesting proposal that would bump compose interpolation into a higher dimension.
Anyway I wonder this is going too far, making compose file a development language on its own. I don't want we end up with LUA scripting inside compose.yaml

**Comment by Vigilans** [comment]
@ndeloof Thanks for your comment!

I want to make some arguments on your concern about whether this is "going too far":

### 1. This proposal is an implementation of https://github.com/compose-spec/compose-spec/issues/248, introducing pre-defined variables

https://github.com/compose-spec/compose-spec/issues/248 brings out the concept of `pre-defined variables`, and has proposed some variables similar with those in this thread:

| Variable	| Description |
| ---- | ---- |
| filePath (or compose.filePath)|	(default) path is relative to the compose-file in which it's defined|
| projectPath (or compose.projectPath)|	path is relative to the project directory (root of the project, or as passed through --project-directory|
| projectRoot (or compose.projectRoot)|	TBD: path is relative to the root of the project (will NOT be overridden by --project-directory)|
| projectName (compose.projectName)|	name of the project (unrelated to the problem description, but for consideration 😅)|

`compose.filePath` is written just like `compose[config-dir]`, only that the dot separator is replaced with brackets here.

In our proposal, the `${name[key]}` form is inspired by bash's associative array:
```shell
$ echo ${example_array[key1]}
```

As `$VAR`, `${VAR}`, `${VAR:-default}`, `${VAR:+presence}` is derived from shell script's syntax, `${name[key]}` is just a nature extension that also sticks to the domain of shell script, not going further to more powerful development language.

The choice of `${name[key]}` has other benefits, like indexing labels, as in common practice label is dot-separated, e.g. `${labels[com.docker.compose.project]}`. The `compose.filePath` form will be incompatible with it.

### 2. Kubernetes has similar concept for exposing pod information to config ([Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/))

Kubernetes already supports declaring environment variable that derives from pod's own metadata or spec config:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
  labels:
    mylabel: labels-fieldref
spec:
  containers:
    - name: test-container
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['mylabel']
```

Since Kubernetes does not support templating mechanism, it adopts the `valueFrom` and `fieldRef` key for referencing metadata and spec variables. In our proposal we introduce these variables using interpolation.

Though, we may take it's form as reference and adopt syntax like `compose.config-dir`, `service.containers.0.env[MY_VAR]`, using dot as separator, and bracket form is only used for `env` and `labels`.

### 3. Named mappings are not going beyond "variables" scope to "development language"

Named mappings are sticking to variables based on following observations:

They can be retrieved using `docker compose config --variables`. e.g. `${name[key]:-default}` will be parsed as variable `name[key]` and default value `default`.

No calculation can be applied on named mappings variables. e.g. `compose.filePath` is not so useful as we are more relying on config's directory, and need to strip the filename part (`compose.yml`). But there's no such thing as `${dirname[${compose[config-file]}]}`, instead only `${compose[config-dir]}` is provided. 

Similarly, when we want the replica index to start at 1, there is no such thing as `${container[replica-index] + 1}`, but another variable `${container[replica-index-1]}` is provided.

Also, no complex filtering mechanism is applied on services indexing, e.g. `${services[label=nas.profile=minio]}`.

Therefore, named mappings are designed to be an extension to environment variables that works more statically.
