### ISSUE TITLE
Can we have Containerfile support?

### ISSUE THREAD

**Issue by purplesyringa** [compose-spec/compose-spec#577]
Currently, Compose Build forces us to use the following to build a service from a `Containerfile`:

```yaml
services:
  app:
    build:
      dockerfile: Containerfile
```

compared to:

```yaml
services:
  app:
    build: .
```

for `Dockerfile`. As Docker is becoming more and more runtime-agnostic and Compose itself uses `compose.yaml`, can we have `Containerfile` as the `build.dockerfile` fallback?
