### ISSUE TITLE
Consider support for compose v2 `extends`

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#67]
**What is the problem you're trying to solve**
`extends` was supported in compose file format v2 and removed in v3. Has since be requested by many users, see https://github.com/moby/moby/issues/31101

**Describe the solution you'd like**
Re-introduce this feature, with a full description so we don't suffer implementation glitches between docker-compose's _de facto_ python implementation and compose-go

**Additional context**
see https://github.com/docker/compose/issues/4315 for debates about the validity of this feature and it's drawbacks. Also consider option to use of compose file overrides and yaml anchors to achieve comparable results.

**Comment by hangyan** [comment]
+1 for the `extends` feature. It's not a ideal solution, but it's still better than compose file overrides and yaml anchors

**Comment by EricHripko** [comment]
Given that Compose spec is aiming to focus at the "inner loop" of the development workflow, I wonder if anchors are sufficient. The examples of `extends` seem to mostly revolve around deployment and deployment-time configuration. In contrast to this, when doing local development, I've not found any substantial cases that weren't solved by a single `.yaml` file (occasionally with anchors).

**Comment by SuperSandro2000** [comment]
If I want to apply the following to all my containers the last time I checked yaml anchors weren't merged deeply so I needed to fall back to ``extends`` which blocks me from upgrading to a newer compose version without writing my own templating engine.

```
services:
  common:
    mem_limit: 64M
    memswap_limit: 0
    cap_drop:
      - all
    cap_add:
      # chown
      - chown
      # ls
      - dac_override
      # su-exec
      - setgid
      - setuid
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - $HOME/docker-compose-files/default.env
    restart: unless-stopped
```

**Comment by EricHripko** [comment]
_High-level description for this is as follows. Will dig into `docker-compose` code in a moment._

Extend another service, in the current file or another, optionally overriding configuration. You can use `extends` on any service together with other configuration keys. The `extends` value must be a dictionary defined with a required `service` and an optional `file` key.

Example:
```yaml
extends:
  file: common.yml
  service: webapp
```

The service the name of the service being extended, for example `web` or `database`. The `file` is the location of a Compose configuration file defining that service.

If you omit the `file` Compose looks for the service configuration in the current file. The `file` value can be an absolute or relative path. If you specify a relative path, Compose treats it as relative to the location of the current file.

You can extend a service that itself extends another. You can extend indefinitely. Compose does not support circular references and docker-compose returns an error if it encounters one.
