### ISSUE TITLE
Add option to specify services to be started by default

### ISSUE THREAD

**Issue by acran** [compose-spec/compose-spec#87]
## The Problem / Use Case
`docker-compose` is often used as a simple way to setup and run an application locally for development purposes. For this not always _all_ defined services are required to run - or additional services may be useful for development. But starting the application with a simple `docker-compose up` without explicitly specifying a list of services always starts _all_ defined services.

For example: I like to define an additional service running _phpMyAdmin_ alongside a mysql database service in order to have a convenient way to inspect and manipulate the database in development. But this service should only ever run in development and may even there be optional/only started on-demand. 

Currently the recommended way for this use case is to split the services into multiple files and pass them on the command line
~~~sh
docker-compose -f docker-compose.dev.yml up
~~~

Since the additional services may depend on (e.g. the database service) or extend already defined services this may require to combine multiple files when starting the development environment:
~~~sh
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
~~~

In an automated environment this is no issue since it just needs to be scripted once. But in a development environment this is a huge inconvenience for the developer:
* the command lines become very long to type instead of a simple `docker-compose up`
* the developer has to remember/lookup which services are defined in which files and pass them as parameters
* the same set of files needs to be passed to _every_ `docker-compose` command since services defined in other files will be ignored, i.e. one can not just stop the application with `docker-compose stop`/`docker-compose down` since the additional services will be ignored

This is a real pain for developers which is why various solutions to this issue were repeatedly requested over years, see linked issues below.

## The desired new feature
There should be a simple way to define the set of "default services" that are started when `docker-compose up` is called without any arguments.
This way additional services can still be defined _in the same_ `docker-compose.yml` file which can then be _started on-demand_:
~~~sh
# start set of "default services"
docker-compose up -d

# start additional service for development
docker-compose up phpmyadmin
~~~

There are various ways the default set could be specified in the `docker-compose.yml` file:
1. provide a file-wide (white)list of services to be started by default, which when not specified defaults to _all_ defined services
2. specify a (black)list of services which should _not_ be started by default but only when explicitly listed or when pulled in as a dependency
3. specify on a per service basis if it should be included in the default set or not; when not specified, the service will be included

## Additional context
This or a similar feature was requested for `docker-compose` repeatedly and in the discussions many more example use cases were explained by the users showing this is a real pain point for them:
docker/compose#6742 (most recent discussion), docker/compose#1896 (main discussion), docker/compose#697, docker/compose#912, docker/compose#1294, docker/compose#1439, docker/compose#1547, docker/compose#2803, docker/compose#3027, docker/compose#3289

Further related issues: docker/compose#1661, docker/compose#1988, docker/compose#2773, docker/compose#3684, docker/compose#4096, docker/compose#4650, docker/compose#6676

### Personal note
I am missing such a feature with `docker-compose` since a very long time. I think it can be implemented with quite reasonable effort but provides an **immense improvement** convenience-wise for local development.
One possible solution I already have implemented which I will explain in the comments.

I'm very committed to making this feature happen whether with my proposed solution or any other different way which I'm also open too. My desired outcome is the improved developer-convenience for the presented use case.
So I am grateful for any feedback and suggestions!

**Comment by acran** [comment]
### proposed option `auto_up` per service

In https://github.com/docker/compose/pull/7548 I created a PR for `docker-compose` which adds an optional flag `auto_up` to services:
* if not specified or set to `true`: the service will start by default - this is the current behavior
* if set to `false`: the service will only be started when explicitly listed as an argument or when pulled in as a dependency of another service

The flag only affects `docker-compose up` and `docker-compose create`. Other command will still operate on _all_ defined services (`docker-compose stop`, `docker-compose down`, `docker-compose ps` etc.). As an example consider this `docker-compose.yml`:
~~~yml
version: '3.8'
services:
  service1:
    image: alpine
    command: echo "I'm service 1"

  service2:
    auto_up: false
    image: alpine
    command: echo "I'm service 2"

  service3:
    image: alpine
    depends_on:
      - service1
      - service2
    command: echo "I'm service 3"

  service4:
    auto_up: false
    image: alpine
    depends_on:
      - service2
    command: echo "I'm service 4"
~~~

With this `docker-compose` would behave as follows:
~~~sh
docker-compose up service1 # starts only service1
docker-compose up service2 # starts only service2

docker-compose up
# starts service1, service2, service3:
# service4 is skipped because of auto_up: false
# service2 is pulled in as dependency of service3

docker-compose up service4 # starts service4, and service2 as its dependency

docker-compose stop # stops all (4) services

docker-compose down # stops and removes all (4) services
# note that --remove-orphans is not needed here

docker-compose logs # shows logs of all 4 services
~~~

For more details see https://github.com/docker/compose/pull/7548

The proposed name of the flag (`auto_up`) up for debate since it is only the next best name I could make up for it :P

In my opinion a service-based flag (3.) is the best solution for this use case, since a file-wide whitelist (1.) or file-wide blacklist (2.) get confusing really fast when extending and merging multiple `docker-compose.yml` files together.

**Comment by karolz-ms** [comment]
Introducing a concept of "default service" can be helpful for development scenarios, but it is a slippery slope when [deployments](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#replicas) are concerned. History of [similar mechanism in Microsoft Service Fabric](https://stackoverflow.com/questions/50441340/auto-creation-of-service-without-defaultservices-on-developer-machines/50445801#50445801) might be instructive

**Comment by acran** [comment]
Just to clarify: I don't think we need to introduce a distinctly new _concept_ of "default services" here since the very only difference is whether that service should be started by default, i.e. when `docker-compose up` is called without arguments. That one property aside it is an ordinary service like now.

**Comment by timwsuqld** [comment]
Some of the issues linked have 250 :+1: before the issue got locked. This is something that the people want, and the work has been done to make it possible. Please consider accepting this proposal, even if we need to discuss some of the naming/mechanics

**Comment by bhazard** [comment]
Love @acran 's `auto_up' flag solution.  We can then drive from `.env` files. Default to `true` and we are golden.

**Comment by ndeloof** [comment]
Also see discussion on https://github.com/docker/compose/issues/7539

I personnaly prefer a `profile` approach as this one offers more flexibility than a boolean "auto_up" to cover more use-cases (dev/test/debug/cleanup...) see https://github.com/docker/compose/issues/7539#issuecomment-645361324

**Comment by EricHripko** [comment]
^ I like the example in the linked comment 🙌 In the context of developing locally, this can provide an easy way to filter out any additional services `compose.yaml` has for integration/system tests. On the flip side, in CI environment you could then toggle the "profile" to include tests and this way easily pick up exit codes/logs from the expected services.

**Comment by acran** [comment]
> I personnaly prefer a `profile` approach as this one offers more flexibility than a boolean "auto_up" to cover more use-cases (dev/test/debug/cleanup...)

Following a profiles approach `auto_up: true` / omitting would map to a `profiles: ["default"]` on the service, `auto_up: false` would map to `profiles: []` or a dummy `profiles: ["never"]`.
So `auto_up` is just a special case of the `profiles` approach, i.e. that approach would indeed support even more use cases :+1:

**Comment by malyzeli** [comment]
As for `profiles`, I believe in more complex configurations it might actually improve readability if the method of defining profiles is inverted. 

Not sure how to express it in a sentence properly, so here is an example:

```yaml
services:

  # react app served from webpack-dev-server
  frontend-dev:
    profiles: ["dev-local", "dev-fullstack", "test-integration"]

  # react app hosted on nginx
  frontend-prod:
    profiles: ["build-prod"]

  # php rest api server
  backend:
    profiles: ["dev-fullstack", "build-prod"]

  # local database for dev (prod database is hosted externally)
  database:
    profiles: ["dev-fullstack"]

  # catalog of react components for development
  storybook:
    profiles: ["dev-local", "dev-fullstack"]

  frontend-test-unit:
    profiles: ["test-unit"]

  # test runner using puppeteer to interact with frontend-dev
  frontend-test-integration:
    profiles: ["test-integration"]

  # generate api docs and publish them to web
  backend-docgen:
    profiles: ["build-prod"]
```

VS

```yaml
services:

  # react app served from webpack-dev-server
  frontend-dev:

  # react app hosted on nginx
  frontend-prod:

  # php rest api server
  backend:

  # local database for dev (prod database is hosted externally)
  database:

  # catalog of react components for development
  storybook:

  # test runner using puppeteer to interact with frontend-dev
  frontend-test:

  # generate api docs and publish them to web
  backend-docgen:

profiles:

  dev-local: 
    - frontend-dev 
    - storybook

  dev-fullstack:
    - frontend-dev
    - backend
    - database

  test-unit:
    - frontend-test-unit

  test-integration:
    - frontend-dev
    - frontend-test-integration

  build-prod:
    - backend
    - backend-docgen
```

Note that my point is not about the syntax, but about the direction of definition flow `service -> profiles` vs `profile -> services`.
