### ISSUE TITLE
Proposal: Scheduled Jobs

### ISSUE THREAD

**Issue by kohidave** [compose-spec/compose-spec#92]
**What is the problem you're trying to solve**
This proposal is to gather community feedback on the idea of adding "scheduled jobs" to the compose-spec. 

## What are scheduled jobs?
A scheduled job is a task which is run at some defined interval (defined by a cron syntax). Unlike services, these executions of the container are ephemeral - they are spun up when it's time, and exit once they're complete. 

## What problem does this solve?
There are many problems that are well suited to being modeled as happening only periodically. Some examples are:

* Sending nightly emails
* Sending notifications to chatrooms
* Purging database records 
* Polling some data source
* Some batch/analytic job

The imagination is the limit on types of workloads that can be modeled as scheduled jobs!

## Is there a need for this?

There's certainly president. There are lots of third party tools which helps customers model their scheduled jobs via docker-compose. The [Ofelia](https://github.com/mcuadros/ofelia#readme) project, for example, exposes the schedule that a command should be run via labels on a service.

So another question would be, why not just follow this model - allow customers to set up services and tag them with some metadata? I think this model works well - but it forces people to write their scheduled jobs as services. While this works fine locally, as customers transition their compose apps to cloud, they'll be faced with the fact that services are often more expensive (operationally and financial) than a simple scheduled job. 
  
## What might it look like?

```yaml
services:
  web:
    build: ./web-app
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
jobs:
  email-sender:
    schedule: @daily
    build: ./email-sender
    command: bundle exec send-email
    environment:
      from: david@kohidave.dev
    depends_on:
      -db
```

**Comment by EricHripko** [comment]
At first sight, I'm leaning more towards the latter model. A lot of this is because attaching a job to an existing service makes it easier to reason with the lifecycle of scheduled jobs and their overall representation locally. Of course, the price of this is that users will have to potentially cram multiple stacks and extra dependencies into the service container (e.g., if web app is Node.js-based and a worker is in Python).

If job is a new runtime concept, we need to ponder on things like:
- What happens if one of the job dependencies is down or unhealthy?
- How is the lifecycle of jobs and services related? For example, if I bring down the services in the project, should jobs keep running on schedule?
- If a local (developer's) machine is offline, what happens to the jobs? For example, should they all trigger when the machine starts back up or do they wait till next time?

**Comment by decentral1se** [comment]
I would say from the amount of people relying on https://github.com/crazy-max/swarm-cronjob, this is needed.

**Comment by mvandermade** [comment]
I have a suggestion for scheduling jobs in Swarm which is already supported by Compose v3:
```yml
services:
  servicename:
    image: my-job:1.0.0
    deploy:
      restart-policy:
        delay: 1d
```

But... downside of this is that you won't see any running container when running `service ls`.
Also you can't pick a time at which the service is restarted.

_Suggestion_

Perhaps it would be an idea to include a `crontab:` key under `restart-policy:` ? No need then to introduce a new runtime concept.

Example:
```yml
services:
  servicename:
    image: my-job:1.0.0
    deploy:
      restart-policy:
        crontab: @daily entrypoint_cron.sh
```

Where you could argue to have the last argument `entrypoint_cron.sh` as optional, with fallback to the default CMD of the image.
